### ISSUE TITLE
Issue with tools_p

### ISSUE THREAD

**Issue by NoSobriety** [Chaannce/tools_p#1]
https://github.com/Magnito14/tools_p/raw/main/tools_p.mov

**Comment by NoSobriety** [comment]
FIX THE ISSUE

**Comment by Lux-14** [comment]
tools_penis

**Comment by Lux-14** [comment]
![](https://share.creavite.co/2cVjWEQlpOnKTp78.gif)

**Comment by ataridiscord** [comment]
https://github.com/Magnito14/tools_p/raw/main/tools_p.mov

**Comment by NoSobriety** [comment]
CHANCE

**Comment by ataridiscord** [comment]
https://user-images.githubusercontent.com/84478811/213786602-6717c62f-b2c5-41ff-bf81-360603cd732a.mp4

**Comment by NoSobriety** [comment]
WELCOME TO YOUR FINAL TEST

**Comment by NoSobriety** [comment]
I'M MR. BEAST

**Comment by Lux-14** [comment]
WE CAN SCRAP THE S

**Comment by Lux-14** [comment]
CAUSE' I NEVER MISS A BEAT

**Comment by Chaannce** [comment]
cool issue, ill take some time to look into it!

**Comment by Lux-14** [comment]
> Reference in ne
