### ISSUE TITLE
chance btw it looks the same but when u try an send messge it sys something

### ISSUE THREAD

**Issue by Lux-14** [Chaannce/tools_p#4]
![image](https://user-images.githubusercontent.com/116319972/213843510-691919f7-068d-4dfc-b544-b1d2fdf01755.png)

**Comment by Chaannce** [comment]
ah ok

**Comment by Lux-14** [comment]
yes im very pro

**Comment by Lux-14** [comment]
https://cdn.discordapp.com/attachments/1060406649417891992/1066210891412025364/call_of_duty_cold_war_2_leaked_trailer_official_activisionblizzard_360p.mp4

**Comment by Lux-14** [comment]
https://user-images.githubusercontent.com/116319972/213843789-3cf6d5f6-0dd3-419f-96db-190e0305f895.mp4
